import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fresca = localFont({
  src: [
    { path: "../public/fonts/Fresca-Regular.ttf", weight: "400" }
  ],
  variable: "--font-fresca",
})

const fruktur = localFont({
  src: [
    { path: "../public/fonts/Fruktur-Regular.ttf", weight: "400" }
  ],
  variable: "--font-fruktur",
})

const fustat = localFont({
  src: [
    { path: "../public/fonts/Fustat-Regular.ttf", weight: "400" }
  ],
  variable: "--font-fustat",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fresca.variable} ${fruktur.variable} ${fustat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
